export const armaduras = [
  {
    Armadura: "Armadura de Peles",
    Tipo: "Armadura Leve",
    Ingr: "Couro x4, Tecido x2",
    "Redução de Mov.": 0,
    "Preço I": 12,
    "Preço II": 48,
    "Preço III": 192,
    "Preço IV": 769,
    RD: 2,
    "Penalidade de Evasão": -1,
    "Deflexão+ I": 0,
    "Deflexão+ II": 1,
    "Deflexão+ III": 2,
    "Deflexão+ IV": 3,
    "PFs+ I": 4,
    "PFs+ II": 6,
    "PFs+ III": 8,
    "PFs+ IV": 10,
    "Quebra I": 1,
    "Quebra II": 2,
    "Quebra III": 3,
    "Quebra IV": 4,
  },
  {
    Armadura: "Linotórax",
    Tipo: "Armadura Leve",
    Ingr: "Couro x2, Tecido x2, Metal x1",
    "Redução de Mov.": 0,
    "Preço I": 11,
    "Preço II": 44,
    "Preço III": 176,
    "Preço IV": 512,
    RD: 2,
    "Penalidade de Evasão": -2,
    "Deflexão+ I": 1,
    "Deflexão+ II": 2,
    "Deflexão+ III": 3,
    "Deflexão+ IV": 4,
    "PFs+ I": 4,
    "PFs+ II": 6,
    "PFs+ III": 8,
    "PFs+ IV": 10,
    "Quebra I": 1,
    "Quebra II": 2,
    "Quebra III": 3,
    "Quebra IV": 4,
  },
  {
    Armadura: "Corselete de Couro",
    Tipo: "Armadura Leve",
    Ingr: "Couro x3",
    "Redução de Mov.": 0,
    "Preço I": 8,
    "Preço II": 32,
    "Preço III": 128,
    "Preço IV": 512,
    RD: 1,
    "Penalidade de Evasão": 0,
    "Deflexão+ I": 0,
    "Deflexão+ II": 1,
    "Deflexão+ III": 2,
    "Deflexão+ IV": 3,
    "PFs+ I": 0,
    "PFs+ II": 2,
    "PFs+ III": 4,
    "PFs+ IV": 6,
    "Quebra I": 1,
    "Quebra II": 2,
    "Quebra III": 3,
    "Quebra IV": 4,
  },
  {
    Armadura: "Jack of Plate",
    Tipo: "Armadura Leve",
    Ingr: "Couro x2, Tecido x2",
    "Redução de Mov.": 0,
    "Preço I": 9,
    "Preço II": 36,
    "Preço III": 144,
    "Preço IV": 576,
    RD: 1,
    "Penalidade de Evasão": 0,
    "Deflexão+ I": 1,
    "Deflexão+ II": 2,
    "Deflexão+ III": 3,
    "Deflexão+ IV": 4,
    "PFs+ I": 2,
    "PFs+ II": 4,
    "PFs+ III": 6,
    "PFs+ IV": 8,
    "Quebra I": 1,
    "Quebra II": 2,
    "Quebra III": 3,
    "Quebra IV": 4,
  },
  {
    Armadura: "Armadura de Escamas",
    Tipo: "Armadura Média",
    Ingr: "Couro x2, Tecido x2, Metal x3",
    "Redução de Mov.": -1,
    "Preço I": 14,
    "Preço II": 54,
    "Preço III": 215,
    "Preço IV": 860,
    RD: 3,
    "Penalidade de Evasão": -3,
    "Deflexão+ I": 4,
    "Deflexão+ II": 5,
    "Deflexão+ III": 6,
    "Deflexão+ IV": 7,
    "PFs+ I": 8,
    "PFs+ II": 10,
    "PFs+ III": 12,
    "PFs+ IV": 24,
    "Quebra I": 2,
    "Quebra II": 3,
    "Quebra III": 4,
    "Quebra IV": 5,
  },
  {
    Armadura: "Jazerino",
    Tipo: "Armadura Média",
    Ingr: "Tecido x3, Couro x1, Metal x2",
    "Redução de Mov.": -1,
    "Preço I": 13,
    "Preço II": 52,
    "Preço III": 208,
    "Preço IV": 832,
    RD: 2,
    "Penalidade de Evasão": 0,
    "Deflexão+ I": 1,
    "Deflexão+ II": 2,
    "Deflexão+ III": 3,
    "Deflexão+ IV": 4,
    "PFs+ I": 4,
    "PFs+ II": 6,
    "PFs+ III": 8,
    "PFs+ IV": 10,
    "Quebra I": 2,
    "Quebra II": 3,
    "Quebra III": 4,
    "Quebra IV": 5,
  },
  {
    Armadura: "Armadura Lamelar",
    Tipo: "Armadura Média",
    Ingr: "Couro x4, Tecido x1, Metal x2",
    "Redução de Mov.": -1,
    "Preço I": 14,
    "Preço II": 56,
    "Preço III": 224,
    "Preço IV": 896,
    RD: 3,
    "Penalidade de Evasão": -1,
    "Deflexão+ I": 2,
    "Deflexão+ II": 3,
    "Deflexão+ III": 4,
    "Deflexão+ IV": 5,
    "PFs+ I": 6,
    "PFs+ II": 8,
    "PFs+ III": 10,
    "PFs+ IV": 12,
    "Quebra I": 2,
    "Quebra II": 3,
    "Quebra III": 4,
    "Quebra IV": 5,
  },
  {
    Armadura: "Dō-maru",
    Tipo: "Armadura Média",
    Ingr: "Couro x3, Tecido x2, Metal x2",
    "Redução de Mov.": -1,
    "Preço I": 16,
    "Preço II": 64,
    "Preço III": 256,
    "Preço IV": 1024,
    RD: 3,
    "Penalidade de Evasão": -1,
    "Deflexão+ I": 3,
    "Deflexão+ II": 4,
    "Deflexão+ III": 5,
    "Deflexão+ IV": 6,
    "PFs+ I": 8,
    "PFs+ II": 10,
    "PFs+ III": 12,
    "PFs+ IV": 24,
    "Quebra I": 2,
    "Quebra II": 3,
    "Quebra III": 4,
    "Quebra IV": 5,
  },
  {
    Armadura: "Couraça",
    Tipo: "Meia-Armadura",
    Ingr: "Metal x2, Couro x1",
    "Redução de Mov.": 0,
    "Preço I": 10,
    "Preço II": 40,
    "Preço III": 160,
    "Preço IV": 640,
    RD: 2,
    "Penalidade de Evasão": -1,
    "Deflexão+ I": 1,
    "Deflexão+ II": 2,
    "Deflexão+ III": 3,
    "Deflexão+ IV": 4,
    "PFs+ I": 6,
    "PFs+ II": 8,
    "PFs+ III": 10,
    "PFs+ IV": 12,
    "Quebra I": 3,
    "Quebra II": 4,
    "Quebra III": 5,
    "Quebra IV": 6,
  },
  {
    Armadura: "Armadura Laminar",
    Tipo: "Meia-Armadura",
    Ingr: "Metal x3, Couro x1, Tecido x1",
    "Redução de Mov.": 0,
    "Preço I": 15,
    "Preço II": 60,
    "Preço III": 240,
    "Preço IV": 860,
    RD: 3,
    "Penalidade de Evasão": -2,
    "Deflexão+ I": 2,
    "Deflexão+ II": 3,
    "Deflexão+ III": 4,
    "Deflexão+ IV": 5,
    "PFs+ I": 8,
    "PFs+ II": 10,
    "PFs+ III": 12,
    "PFs+ IV": 24,
    "Quebra I": 3,
    "Quebra II": 4,
    "Quebra III": 5,
    "Quebra IV": 6,
  },
  {
    Armadura:
      "Combinações de Helmo, Gorjal, Vambraças, Pauldron, Grevas, ou Escarcela",
    Tipo: "Meia-Armadura",
    Ingr: "Metal x2, Couro x2",
    "Redução de Mov.": 0,
    "Preço I": 12,
    "Preço II": 48,
    "Preço III": 192,
    "Preço IV": 768,
    RD: 2,
    "Penalidade de Evasão": 0,
    "Deflexão+ I": 0,
    "Deflexão+ II": 1,
    "Deflexão+ III": 2,
    "Deflexão+ IV": 3,
    "PFs+ I": 4,
    "PFs+ II": 6,
    "PFs+ III": 8,
    "PFs+ IV": 10,
    "Quebra I": 3,
    "Quebra II": 4,
    "Quebra III": 5,
    "Quebra IV": 6,
  },
  {
    Armadura: "Ō-yoroi",
    Tipo: "Armadura Pesada",
    Ingr: "Couro x6, Tecido x2, Metal x4",
    "Redução de Mov.": -2,
    "Preço I": 40,
    "Preço II": 160,
    "Preço III": 640,
    "Preço IV": 2560,
    RD: 6,
    "Penalidade de Evasão": -3,
    "Deflexão+ I": 5,
    "Deflexão+ II": 6,
    "Deflexão+ III": 7,
    "Deflexão+ IV": 8,
    "PFs+ I": 14,
    "PFs+ II": 16,
    "PFs+ III": 18,
    "PFs+ IV": 20,
    "Quebra I": 4,
    "Quebra II": 5,
    "Quebra III": 6,
    "Quebra IV": 7,
  },
  {
    Armadura: "Armadura de Talas",
    Tipo: "Armadura Pesada",
    Ingr: "Metal x6, Couro x4, Tecido x2",
    "Redução de Mov.": -2,
    "Preço I": 30,
    "Preço II": 120,
    "Preço III": 480,
    "Preço IV": 1920,
    RD: 6,
    "Penalidade de Evasão": -5,
    "Deflexão+ I": 6,
    "Deflexão+ II": 7,
    "Deflexão+ III": 8,
    "Deflexão+ IV": 9,
    "PFs+ I": 14,
    "PFs+ II": 16,
    "PFs+ III": 18,
    "PFs+ IV": 20,
    "Quebra I": 4,
    "Quebra II": 5,
    "Quebra III": 6,
    "Quebra IV": 7,
  },
  {
    Armadura: "Broigne",
    Tipo: "Armadura Pesada",
    Ingr: "Tecido x4, Metal x3, Couro x2",
    "Redução de Mov.": -2,
    "Preço I": 20,
    "Preço II": 80,
    "Preço III": 320,
    "Preço IV": 1280,
    RD: 5,
    "Penalidade de Evasão": -4,
    "Deflexão+ I": 5,
    "Deflexão+ II": 6,
    "Deflexão+ III": 7,
    "Deflexão+ IV": 8,
    "PFs+ I": 12,
    "PFs+ II": 14,
    "PFs+ III": 16,
    "PFs+ IV": 18,
    "Quebra I": 4,
    "Quebra II": 5,
    "Quebra III": 6,
    "Quebra IV": 7,
  },
  {
    Armadura: "Cota de Malha",
    Tipo: "Armadura Pesada",
    Ingr: "Metal x8",
    "Redução de Mov.": -2,
    "Preço I": 26,
    "Preço II": 104,
    "Preço III": 416,
    "Preço IV": 1664,
    RD: 5,
    "Penalidade de Evasão": -3,
    "Deflexão+ I": 4,
    "Deflexão+ II": 5,
    "Deflexão+ III": 6,
    "Deflexão+ IV": 7,
    "PFs+ I": 12,
    "PFs+ II": 14,
    "PFs+ III": 16,
    "PFs+ IV": 18,
    "Quebra I": 4,
    "Quebra II": 5,
    "Quebra III": 6,
    "Quebra IV": 7,
  },
  {
    Armadura: "Armadura de Placas",
    Tipo: "Armadura Pesada",
    Ingr: "Metal x10, Tecido x4, Couro x6",
    "Redução de Mov.": -3,
    "Preço I": 48,
    "Preço II": 192,
    "Preço III": 768,
    "Preço IV": 3072,
    RD: 8,
    "Penalidade de Evasão": -6,
    "Deflexão+ I": 8,
    "Deflexão+ II": 9,
    "Deflexão+ III": 10,
    "Deflexão+ IV": 11,
    "PFs+ I": 16,
    "PFs+ II": 18,
    "PFs+ III": 20,
    "PFs+ IV": 22,
    "Quebra I": 4,
    "Quebra II": 5,
    "Quebra III": 6,
    "Quebra IV": 7,
  },
];
